### ISSUE TITLE
Automated remote testing setup

### ISSUE THREAD

**Issue by neuschaefer** [neuschaefer/wpcm450#27]
## Purpose

I want to test things without carrying server boards around. Some boards fit into my backpack, others simply don't. In any case, setup and teardown takes time and space, which is a bit annoying.

## Design

- A _control server_ always runs, and it can be reached via SSH.
- The _switchbox_ is a enclosure with relays that supply power (5V, 12V, 230V, etc.) to different devices
- Switches (relays) are controlled via the _switchbox microcontroller_, which accepts commands via UART or USB
- A _device under test (DUT)_ has some of the following connections:
  - power supply: via a switch
  - UART for debug control
  - Ethernet
  - perhaps a flash programmer

## TODO

- [ ] Build/document switchbox
- [ ] Write switchbox firmware
- [ ] hook up some boards
- [ ] evaluate [Lava](https://www.lavasoftware.org/index.html)
- [ ] write automated test suite
